name: Check
on:
  pull_request:
jobs:
  detekt:
    name: Detekt Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: cache-gradle-

      - name: Setup Java 15
        uses: actions/setup-java@v1
        with:
          java-version: '15'

      - name: Run Detekt
        run: ./gradlew detekt --stacktrace

      - name: Stop Gradle
        run: ./gradlew --stop
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: cache-gradle-

      - name: Setup Java 15
        uses: actions/setup-java@v1
        with:
          java-version: '15'

      - name: Run Debug Unit Tests
        run: ./gradlew test --stacktrace

      - name: Stop Gradle
        run: ./gradlew --stop
  ui-tests:
    name: FTL UI Tests
    needs: [unit-tests, detekt]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: cache-gradle-

      - name: Setup Java 15
        uses: actions/setup-java@v1
        with:
          java-version: '15'

      - name: Build app and test APKs
        run: ./gradlew :sample:assembleDebug && ./gradlew  :sample:assembleDebugAndroidTest

      - name: Login to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Use gcloud CLI
        run: gcloud info

      - name: Set current project
        run: gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Run Instrumentation Tests in Firebase Test Lab
        run: gcloud firebase test android run --type instrumentation --app sample/build/outputs/apk/debug/sample-debug.apk --test sample/build/outputs/apk/androidTest/debug/sample-debug-androidTest.apk --device model=Pixel2,version=28,locale=en,orientation=portrait

      - name: Stop Gradle
        run: ./gradlew --stop
  compatibility-check:
    name: Compatibility Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: cache-gradle-

      - name: Setup Java 15
        uses: actions/setup-java@v1
        with:
          java-version: '15'

      - name: Check API compatibility
        run: ./gradlew apiCheck

      - name: Stop Gradle
        run: ./gradlew --stop
