name: Publish Snaphot
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-maven-snapshot:
    name: Deploy To Maven Snaphot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: cache-gradle-

      - name: Setup Java 15
        uses: actions/setup-java@v1
        with:
          java-version: '15'

      - name: Deploy Snapshot
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
        run: ./gradlew publish --no-daemon --no-parallel --stacktrace


      - name: Stop Gradle
        run: ./gradlew --stop
